# Generated by Django 5.0.6 on 2024-06-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participants',
            new_name='members',
        ),
    ]
